import { damageComponent, standardDamage } from '../../combat/DamageComponentPresets';
import { Hero } from '../../entities/Hero';
import { SkillId } from '../SkillId';
import { BASIC_ATTACK_SKILL } from './BasicAttackSkill';
import { applySkillCombatOverride } from '../HeroCombatOverrides';
import { CatalogCombatSkillDefinition, CombatSkillDefinition } from './CombatSkillDefinition';

export { BASIC_ATTACK_SKILL } from './BasicAttackSkill';

export const HERO_COMBAT_SKILL_CATALOG: CatalogCombatSkillDefinition[] = [
  BASIC_ATTACK_SKILL,
  {
    skillId: 'blessing',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 72,
    initialCooldown: 2,
    cooldownTurns: 6,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 6,
    attributeFactor: 0.45,
    effectDurationTurns: 3,
  },
  {
    skillId: 'minor_heal',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 100,
    initialCooldown: 0,
    cooldownTurns: 3,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 30,
    attributeFactor: 0.35,
    healConditionThreshold: 0.85,
  },
  {
    skillId: 'fireball',
    kind: 'damage',
    damageComponents: standardDamage('fire', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 90,
    initialCooldown: 4,
    cooldownTurns: 4,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 18,
    attributeFactor: 0.7167,
    onHitDot: { element: 'fire', damagePerTurn: 5, durationTurns: 3, applyChance: 0.6 },
  },
  {
    skillId: 'arcane_bolt',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 80,
    initialCooldown: 0,
    cooldownTurns: 2,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 12,
    attributeFactor: 1.025,
  },
  {
    skillId: 'frost_shard',
    kind: 'damage',
    damageComponents: standardDamage('cold', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 78,
    initialCooldown: 0,
    cooldownTurns: 2,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 15,
    attributeFactor: 0.8,
  },
  {
    skillId: 'blizzard',
    kind: 'damage',
    damageComponents: standardDamage('cold', 'all', { delivery: 'aoe' }),
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 86,
    initialCooldown: 4,
    cooldownTurns: 5,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 15,
    attributeFactor: 1.1,
    onHitDot: { element: 'cold', damagePerTurn: 3, durationTurns: 2, applyChance: 0.55 },
  },
  {
    skillId: 'smite',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single', {
      delivery: 'melee',
      extras: [damageComponent('physical', 'melee', 0.3)],
    }),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 75,
    initialCooldown: 0,
    cooldownTurns: 2,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 15,
    attributeFactor: 0.72,
  },
  {
    skillId: 'arcane_touch',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 50,
    initialCooldown: 0,
    cooldownTurns: 0,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 0,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 5,
    attributeFactor: 0.82,
  },
  {
    skillId: 'thrust',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'melee' }),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 60,
    initialCooldown: 0,
    cooldownTurns: 4,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 15,
    attributeFactor: 0.72,
  },
  {
    skillId: 'power_attack',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'melee' }),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    targetPriorityPercent: 90,
    usePriority: 40,
    initialCooldown: 0,
    cooldownTurns: 2,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 9,
    attributeFactor: 0.6333,
  },
  {
    skillId: 'precise_shot',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'projectile' }),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 70,
    initialCooldown: 0,
    cooldownTurns: 2,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 15,
    attributeFactor: 0.95,
  },
  {
    skillId: 'piercing_arrow',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'projectile' }),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    targetPriorityPercent: 85,
    usePriority: 82,
    initialCooldown: 1,
    cooldownTurns: 3,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 18,
    attributeFactor: 1.05,
  },
  {
    skillId: 'arrow_rain',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'all', { delivery: 'aoe' }),
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 88,
    initialCooldown: 3,
    cooldownTurns: 5,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 15,
    attributeFactor: 0.85,
  },
  {
    skillId: 'marked_prey',
    kind: 'debuff_defense',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    usePriority: 76,
    initialCooldown: 1,
    cooldownTurns: 5,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 6,
    attributeFactor: 0.55,
    effectDurationTurns: 3,
  },
  {
    skillId: 'sag_clr_light',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 82,
    initialCooldown: 0,
    cooldownTurns: 2,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 15,
    attributeFactor: 0.8,
  },
  {
    skillId: 'sag_clr_smite',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    usePriority: 80,
    initialCooldown: 0,
    cooldownTurns: 4,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 15,
    attributeFactor: 0.86,
  },
  {
    skillId: 'sag_clr_ward',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 73,
    initialCooldown: 2,
    cooldownTurns: 8,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 6,
    attributeFactor: 0.45,
    effectDurationTurns: 3,
  },
  {
    skillId: 'sag_alt_radiance',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 108,
    initialCooldown: 2,
    cooldownTurns: 6,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 24,
    attributeFactor: 0.3625,
    healConditionThreshold: 0.88,
  },
  {
    skillId: 'sag_alt_chorus',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 77,
    initialCooldown: 4,
    cooldownTurns: 8,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 6,
    attributeFactor: 0.5,
    effectDurationTurns: 3,
  },
  {
    skillId: 'sag_alt_sanctuary',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 104,
    initialCooldown: 4,
    cooldownTurns: 8,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 15,
    attributeFactor: 0.4,
    healConditionThreshold: 0.78,
  },
  {
    skillId: 'sag_san_grace',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 112,
    initialCooldown: 2,
    cooldownTurns: 6,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 30,
    attributeFactor: 0.34,
    healConditionThreshold: 0.9,
  },
  {
    skillId: 'sag_san_judgment',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    usePriority: 91,
    initialCooldown: 2,
    cooldownTurns: 6,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 21,
    attributeFactor: 0.8143,
  },
  {
    skillId: 'sag_san_benediction',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 84,
    initialCooldown: 4,
    cooldownTurns: 10,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 9,
    attributeFactor: 0.4667,
    effectDurationTurns: 4,
  },
  {
    skillId: 'vid_clr_renew',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 109,
    initialCooldown: 0,
    cooldownTurns: 6,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 24,
    attributeFactor: 0.35,
    healConditionThreshold: 0.87,
  },
  {
    skillId: 'vid_clr_bloom',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 102,
    initialCooldown: 2,
    cooldownTurns: 8,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 12,
    attributeFactor: 0.425,
    healConditionThreshold: 0.8,
  },
  {
    skillId: 'vid_clr_touch',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 111,
    initialCooldown: 0,
    cooldownTurns: 4,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 18,
    attributeFactor: 0.4,
    healConditionThreshold: 0.92,
  },
  {
    skillId: 'vid_gua_aegis',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 75,
    initialCooldown: 4,
    cooldownTurns: 8,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 6,
    attributeFactor: 0.5,
    effectDurationTurns: 3,
  },
  {
    skillId: 'vid_gua_pulse',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 106,
    initialCooldown: 4,
    cooldownTurns: 8,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 18,
    attributeFactor: 0.3833,
    healConditionThreshold: 0.82,
  },
  {
    skillId: 'vid_gua_spring',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 110,
    initialCooldown: 2,
    cooldownTurns: 6,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 27,
    attributeFactor: 0.3556,
    healConditionThreshold: 0.85,
  },
  {
    skillId: 'vid_fil_dawn',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 113,
    initialCooldown: 2,
    cooldownTurns: 6,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 24,
    attributeFactor: 0.3875,
    healConditionThreshold: 0.88,
  },
  {
    skillId: 'vid_fil_aurora',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 107,
    initialCooldown: 4,
    cooldownTurns: 8,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 21,
    attributeFactor: 0.3714,
    healConditionThreshold: 0.75,
  },
  {
    skillId: 'vid_fil_rebirth',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 115,
    initialCooldown: 6,
    cooldownTurns: 10,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 36,
    attributeFactor: 0.325,
    healConditionThreshold: 0.65,
  },
  {
    skillId: 'oracle_mend',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 110,
    initialCooldown: 0,
    cooldownTurns: 6,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 30,
    attributeFactor: 0.32,
    healConditionThreshold: 0.85,
  },
  {
    skillId: 'oracle_sanctuary',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 105,
    initialCooldown: 6,
    cooldownTurns: 8,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 15,
    attributeFactor: 0.4,
    healConditionThreshold: 0.75,
  },
  {
    skillId: 'mil_guer_cleave',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'all', { delivery: 'aoe' }),
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 84,
    initialCooldown: 0,
    cooldownTurns: 6,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 15,
    attributeFactor: 0.72,
  },
  {
    skillId: 'mil_guer_hold',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 70,
    initialCooldown: 0,
    cooldownTurns: 6,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 6,
    attributeFactor: 0.35,
    effectDurationTurns: 2,
  },
  {
    skillId: 'mil_guer_rally',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 76,
    initialCooldown: 2,
    cooldownTurns: 8,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 6,
    attributeFactor: 0.45,
    effectDurationTurns: 3,
  },
  {
    skillId: 'mil_cap_order',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 80,
    initialCooldown: 4,
    cooldownTurns: 8,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 9,
    attributeFactor: 0.3667,
    effectDurationTurns: 3,
  },
  {
    skillId: 'mil_cap_phalanx',
    kind: 'debuff_defense',
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'highest_hp_percent',
    usePriority: 74,
    initialCooldown: 2,
    cooldownTurns: 6,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 6,
    attributeFactor: 0.45,
    effectDurationTurns: 2,
  },
  {
    skillId: 'mil_cap_lance',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'melee' }),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    targetPriorityPercent: 80,
    usePriority: 86,
    initialCooldown: 0,
    cooldownTurns: 4,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 18,
    attributeFactor: 0.6833,
  },
  {
    skillId: 'mil_gen_decree',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'melee' }),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    usePriority: 92,
    initialCooldown: 2,
    cooldownTurns: 6,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 24,
    attributeFactor: 0.6375,
  },
  {
    skillId: 'mil_gen_banner',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 88,
    initialCooldown: 4,
    cooldownTurns: 10,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 9,
    attributeFactor: 0.4333,
    effectDurationTurns: 4,
  },
  {
    skillId: 'mil_gen_siege',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'all', { delivery: 'aoe' }),
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 90,
    initialCooldown: 4,
    cooldownTurns: 8,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 21,
    attributeFactor: 0.6429,
  },
  {
    skillId: 'mar_gla_slash',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'melee' }),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 83,
    initialCooldown: 0,
    cooldownTurns: 2,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 12,
    attributeFactor: 0.775,
  },
  {
    skillId: 'mar_gla_feint',
    kind: 'debuff_defense',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    usePriority: 68,
    initialCooldown: 0,
    cooldownTurns: 4,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 6,
    attributeFactor: 0.35,
    effectDurationTurns: 2,
  },
  {
    skillId: 'mar_gla_bleed',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'melee' }),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 81,
    initialCooldown: 0,
    cooldownTurns: 4,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 12,
    attributeFactor: 0.675,
    onHitDot: { element: 'air', damagePerTurn: 4, durationTurns: 3, applyChance: 0.75 },
  },
  {
    skillId: 'mar_mes_flow',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'melee' }),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 87,
    initialCooldown: 0,
    cooldownTurns: 2,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 15,
    attributeFactor: 0.76,
  },
  {
    skillId: 'mar_mes_zen',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 72,
    initialCooldown: 2,
    cooldownTurns: 6,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 6,
    attributeFactor: 0.4,
    effectDurationTurns: 3,
  },
  {
    skillId: 'mar_mes_rebuke',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'melee' }),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 85,
    initialCooldown: 0,
    cooldownTurns: 4,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 15,
    attributeFactor: 0.72,
  },
  {
    skillId: 'mar_cam_crown',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'single', { delivery: 'melee' }),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    usePriority: 94,
    initialCooldown: 2,
    cooldownTurns: 6,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 24,
    attributeFactor: 0.7,
  },
  {
    skillId: 'mar_cam_cyclone',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'all', { delivery: 'aoe' }),
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 91,
    initialCooldown: 4,
    cooldownTurns: 8,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 18,
    attributeFactor: 0.7167,
  },
  {
    skillId: 'mar_cam_glory',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 79,
    initialCooldown: 4,
    cooldownTurns: 8,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 21,
    attributeFactor: 0.3143,
    healConditionThreshold: 0.9,
  },
  {
    skillId: 'arc_mag_bolt',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 86,
    initialCooldown: 0,
    cooldownTurns: 2,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 15,
    attributeFactor: 0.82,
  },
  {
    skillId: 'arc_mag_weave',
    kind: 'debuff_defense',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    usePriority: 70,
    initialCooldown: 0,
    cooldownTurns: 4,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 6,
    attributeFactor: 0.35,
    effectDurationTurns: 2,
  },
  {
    skillId: 'arc_mag_ward',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 74,
    initialCooldown: 2,
    cooldownTurns: 8,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 6,
    attributeFactor: 0.45,
    effectDurationTurns: 3,
  },
  {
    skillId: 'arc_arq_nova',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'all', { delivery: 'aoe' }),
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 90,
    initialCooldown: 2,
    cooldownTurns: 6,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 18,
    attributeFactor: 0.7833,
  },
  {
    skillId: 'arc_arq_rift',
    kind: 'damage',
    damageComponents: standardDamage('air', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 88,
    initialCooldown: 2,
    cooldownTurns: 4,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 18,
    attributeFactor: 0.8833,
  },
  {
    skillId: 'arc_arq_bind',
    kind: 'debuff_defense',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    usePriority: 72,
    initialCooldown: 2,
    cooldownTurns: 6,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 6,
    attributeFactor: 0.45,
    effectDurationTurns: 3,
  },
  {
    skillId: 'arc_imp_decree',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 93,
    initialCooldown: 4,
    cooldownTurns: 6,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 24,
    attributeFactor: 0.775,
  },
  {
    skillId: 'arc_imp_crown',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 85,
    initialCooldown: 4,
    cooldownTurns: 10,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 9,
    attributeFactor: 0.4667,
    effectDurationTurns: 4,
  },
  {
    skillId: 'arc_imp_storm',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'all', { delivery: 'aoe' }),
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 91,
    initialCooldown: 4,
    cooldownTurns: 8,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 21,
    attributeFactor: 0.8,
  },
  {
    skillId: 'inn_fei_spark',
    kind: 'damage',
    damageComponents: standardDamage('fire', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 84,
    initialCooldown: 0,
    cooldownTurns: 2,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 12,
    attributeFactor: 0.95,
  },
  {
    skillId: 'inn_fei_whisper',
    kind: 'debuff_defense',
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    usePriority: 69,
    initialCooldown: 0,
    cooldownTurns: 4,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 6,
    attributeFactor: 0.35,
    effectDurationTurns: 2,
  },
  {
    skillId: 'inn_fei_flame',
    kind: 'damage',
    damageComponents: standardDamage('fire', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 87,
    initialCooldown: 0,
    cooldownTurns: 4,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 15,
    attributeFactor: 0.88,
    onHitDot: { element: 'fire', damagePerTurn: 4, durationTurns: 2 },
  },
  {
    skillId: 'inn_sob_comet',
    kind: 'damage',
    damageComponents: standardDamage('fire', 'all', { delivery: 'aoe' }),
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 89,
    initialCooldown: 2,
    cooldownTurns: 6,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 18,
    attributeFactor: 0.8333,
  },
  {
    skillId: 'inn_sob_veil',
    kind: 'buff_attack',
    targetPool: 'heroes',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 76,
    initialCooldown: 2,
    cooldownTurns: 8,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 6,
    attributeFactor: 0.5,
    effectDurationTurns: 3,
  },
  {
    skillId: 'inn_sob_lance',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 86,
    initialCooldown: 0,
    cooldownTurns: 4,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 18,
    attributeFactor: 0.8167,
  },
  {
    skillId: 'inn_fil_ether',
    kind: 'damage',
    damageComponents: standardDamage('air', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 92,
    initialCooldown: 2,
    cooldownTurns: 4,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 21,
    attributeFactor: 0.8429,
  },
  {
    skillId: 'inn_fil_storm',
    kind: 'damage',
    damageComponents: standardDamage('air', 'all', { delivery: 'aoe' }),
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 90,
    initialCooldown: 4,
    cooldownTurns: 8,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 21,
    attributeFactor: 0.7571,
  },
  {
    skillId: 'inn_fil_ascend',
    kind: 'heal_ally',
    targetPool: 'heroes',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 78,
    initialCooldown: 4,
    cooldownTurns: 8,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 21,
    attributeFactor: 0.3143,
    healConditionThreshold: 0.95,
  },
  {
    skillId: 'pyro_inferno',
    kind: 'damage',
    damageComponents: standardDamage('fire', 'all', {
      extras: [damageComponent('physical', 'aoe', 0.15)],
    }),
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 92,
    initialCooldown: 4,
    cooldownTurns: 6,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 21,
    attributeFactor: 0.8143,
  },
  {
    skillId: 'pyro_ember',
    kind: 'damage',
    damageComponents: standardDamage('fire', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 88,
    initialCooldown: 0,
    cooldownTurns: 2,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 15,
    attributeFactor: 0.86,
    onHitDot: { element: 'fire', damagePerTurn: 4, durationTurns: 2 },
  },
  {
    skillId: 'arcane_surge',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 91,
    initialCooldown: 2,
    cooldownTurns: 4,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 18,
    attributeFactor: 0.8833,
  },
  {
    skillId: 'arcane_focus',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 87,
    initialCooldown: 0,
    cooldownTurns: 2,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 15,
    attributeFactor: 0.78,
  },
  {
    skillId: 'inquisitor_judgment',
    kind: 'damage',
    damageComponents: standardDamage('lightning', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'highest_hp_percent',
    usePriority: 86,
    initialCooldown: 0,
    cooldownTurns: 4,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 18,
    attributeFactor: 0.7833,
  },
  {
    skillId: 'inquisitor_flame',
    kind: 'damage',
    damageComponents: standardDamage('fire', 'single'),
    targetPool: 'enemies',
    targetScope: 'single',
    targetPriority: 'lowest_hp_percent',
    usePriority: 83,
    initialCooldown: 0,
    cooldownTurns: 2,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 12,
    attributeFactor: 0.9,
  },
  {
    skillId: 'reaver_cleave',
    kind: 'damage',
    damageComponents: standardDamage('physical', 'all', { delivery: 'aoe' }),
    targetPool: 'enemies',
    targetScope: 'all',
    targetPriority: 'lowest_hp_percent',
    usePriority: 85,
    initialCooldown: 0,
    cooldownTurns: 6,
    actionRecoverySeconds: 0.7,
    cooldownSecondsPerRank: 1.5,
    maxCooldownReduction: 0.45,
    minCooldownReduction: -0.25,
    basePower: 1,
    powerPerRank: 18,
    attributeFactor: 0.6833,
  }
];

const heroSkillMap = new Map(HERO_COMBAT_SKILL_CATALOG.map((skill) => [skill.skillId, skill]));

export function getHeroCombatSkill(skillId: string): CombatSkillDefinition | undefined {
  const base = heroSkillMap.get(skillId);
  return base ? applySkillCombatOverride(base) : undefined;
}

/** Skill do catálogo, sem override do lab. */
export function getCatalogHeroCombatSkill(
  skillId: string,
): CatalogCombatSkillDefinition | undefined {
  return heroSkillMap.get(skillId);
}

export function listHeroCombatSkills(hero: Hero): CombatSkillDefinition[] {
  const props = hero.toProps();

  return props.equippedSkillIds
    .filter((skillId): skillId is SkillId => Boolean(skillId))
    .filter((skillId) => (props.skillRanks[skillId] ?? 0) >= 1)
    .map((skillId) => getHeroCombatSkill(skillId))
    .filter((skill): skill is CombatSkillDefinition => skill !== undefined);
}
