import { SkillDefinition } from './SkillDefinition';
import { isKnightEvolutionId, knightEvolutionUnlocksSkill } from './KnightEvolutionCatalog';
import { isPriestEvolutionId, priestEvolutionUnlocksSkill } from './PriestEvolutionCatalog';
import { isSorcererEvolutionId, sorcererEvolutionUnlocksSkill } from './SorcererEvolutionCatalog';

export const SKILL_CATALOG: SkillDefinition[] = [
  // Universais
  {
    id: 'basic_attack',
    scope: 'universal',
    branch: 'offense',
    name: 'Ataque Básico',
    description: 'Golpe padrão com metade do ATK. Sempre ativo; mais frequente que skills.',
    maxRank: 1,
    requirements: [],
    scaling: 'str',
    pointType: 'improvement',
  },
  {
    id: 'power_attack',
    scope: 'universal',
    branch: 'offense',
    name: 'Ataque Poderoso',
    description: 'Dano físico extra baseado em STR.',
    maxRank: 3,
    requirements: [{ type: 'hero_level', min: 2 }, { type: 'attribute', key: 'str', min: 8 }],
    scaling: 'str',
    pointType: 'improvement',
  },
  // Knight
  {
    id: 'thrust',
    scope: 'class',
    heroClass: 'knight',
    branch: 'offense',
    name: 'Investida Mortal',
    description: 'Golpe pesado do cavaleiro.',
    maxRank: 3,
    requirements: [{ type: 'hero_class', heroClass: 'knight' }, { type: 'hero_level', min: 3 }],
    scaling: 'str',
    pointType: 'improvement',
  },
  // Sorcerer
  {
    id: 'arcane_bolt',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'offense',
    name: 'Raio Arcano',
    description: 'Magia básica de dano.',
    maxRank: 3,
    requirements: [{ type: 'hero_class', heroClass: 'sorcerer' }, { type: 'hero_level', min: 2 }],
    scaling: 'int',
    pointType: 'improvement',
  },
  {
    id: 'fireball',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'offense',
    name: 'Bola de Fogo',
    description: 'Magia de fogo devastadora.',
    maxRank: 3,
    requirements: [
      { type: 'hero_class', heroClass: 'sorcerer' },
      { type: 'skill_rank', skillId: 'arcane_bolt', minRank: 1 },
      { type: 'attribute', key: 'int', min: 12 },
    ],
    scaling: 'int',
    pointType: 'improvement',
  },
  {
    id: 'frost_shard',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'offense',
    name: 'Estilhaço Gélido',
    description: 'Projétil de gelo que atinge um inimigo.',
    maxRank: 3,
    requirements: [{ type: 'hero_class', heroClass: 'sorcerer' }, { type: 'hero_level', min: 2 }],
    scaling: 'int',
    pointType: 'improvement',
  },
  {
    id: 'blizzard',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'offense',
    name: 'Nevasca',
    description: 'Tempestade de gelo em área; pode congelar alvos.',
    maxRank: 3,
    requirements: [
      { type: 'hero_class', heroClass: 'sorcerer' },
      { type: 'skill_rank', skillId: 'frost_shard', minRank: 1 },
      { type: 'attribute', key: 'int', min: 11 },
    ],
    scaling: 'int',
    pointType: 'improvement',
  },
  // Priest
  {
    id: 'minor_heal',
    scope: 'class',
    heroClass: 'priest',
    branch: 'utility',
    name: 'Cura Menor',
    description: 'Cura o aliado mais ferido.',
    maxRank: 3,
    requirements: [{ type: 'hero_class', heroClass: 'priest' }, { type: 'hero_level', min: 2 }],
    scaling: 'int',
    pointType: 'improvement',
  },
  {
    id: 'blessing',
    scope: 'class',
    heroClass: 'priest',
    branch: 'utility',
    name: 'Bênção',
    description: 'Fortalece a party.',
    maxRank: 2,
    requirements: [
      { type: 'hero_class', heroClass: 'priest' },
      { type: 'skill_rank', skillId: 'minor_heal', minRank: 1 },
    ],
    scaling: 'int',
    pointType: 'improvement',
  },
  {
    id: 'smite',
    scope: 'class',
    heroClass: 'priest',
    branch: 'offense',
    name: 'Castigo',
    description: 'Dano sagrado ao inimigo.',
    maxRank: 3,
    requirements: [
      { type: 'hero_class', heroClass: 'priest' },
      { type: 'attribute', key: 'int', min: 10 },
    ],
    scaling: 'int',
    pointType: 'improvement',
  },
  // Archer — Rain
  {
    id: 'precise_shot',
    scope: 'class',
    heroClass: 'archer',
    branch: 'offense',
    name: 'Tiro Preciso',
    description: 'Flecha limpa à distância. Escala com DEX.',
    maxRank: 3,
    requirements: [{ type: 'hero_class', heroClass: 'archer' }, { type: 'hero_level', min: 2 }],
    scaling: 'dex',
    pointType: 'improvement',
  },
  {
    id: 'piercing_arrow',
    scope: 'class',
    heroClass: 'archer',
    branch: 'offense',
    name: 'Flecha Perfurante',
    description: 'Disparo que ignora parte da postura do alvo.',
    maxRank: 3,
    requirements: [
      { type: 'hero_class', heroClass: 'archer' },
      { type: 'skill_rank', skillId: 'precise_shot', minRank: 1 },
      { type: 'hero_level', min: 4 },
    ],
    scaling: 'dex',
    pointType: 'improvement',
  },
  {
    id: 'arrow_rain',
    scope: 'class',
    heroClass: 'archer',
    branch: 'offense',
    name: 'Chuva de Flechas',
    description: 'Rajada cobrindo todos os inimigos — o nome não é coincidência.',
    maxRank: 3,
    requirements: [
      { type: 'hero_class', heroClass: 'archer' },
      { type: 'skill_rank', skillId: 'piercing_arrow', minRank: 1 },
      { type: 'hero_level', min: 6 },
      { type: 'attribute', key: 'dex', min: 16 },
    ],
    scaling: 'dex',
    pointType: 'improvement',
  },
  {
    id: 'marked_prey',
    scope: 'class',
    heroClass: 'archer',
    branch: 'utility',
    name: 'Presa Marcada',
    description: 'Marca o alvo, reduzindo sua defesa por alguns turnos.',
    maxRank: 2,
    requirements: [
      { type: 'hero_class', heroClass: 'archer' },
      { type: 'hero_level', min: 3 },
      { type: 'attribute', key: 'dex', min: 12 },
    ],
    scaling: 'dex',
    pointType: 'improvement',
  },
  // Evolução Galneon — Caminho Militar · Guerreiro
  {
    id: 'mil_guer_cleave',
    scope: 'class',
    heroClass: 'knight',
    branch: 'offense',
    name: 'Corte em Linha',
    description: 'Golpe amplo que fere vários inimigos.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'knight_military_guerreiro' }],
    scaling: 'str',
    pointType: 'ascension',
    ascensionId: 'knight_military_guerreiro',
  },
  {
    id: 'mil_guer_hold',
    scope: 'class',
    heroClass: 'knight',
    branch: 'defense',
    name: 'Postura de Guarda',
    description: 'Reduz o dano recebido por um breve período.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'knight_military_guerreiro' }],
    scaling: 'str',
    pointType: 'ascension',
    ascensionId: 'knight_military_guerreiro',
  },
  {
    id: 'mil_guer_rally',
    scope: 'class',
    heroClass: 'knight',
    branch: 'utility',
    name: 'Chamado às Armas',
    description: 'Inspira aliados com bônus de ataque.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'knight_military_guerreiro' }],
    scaling: 'str',
    pointType: 'ascension',
    ascensionId: 'knight_military_guerreiro',
  },
  // Caminho Militar · Capitão
  {
    id: 'mil_cap_order',
    scope: 'class',
    heroClass: 'knight',
    branch: 'utility',
    name: 'Ordem de Comando',
    description: 'Fortalece toda a equipe em combate.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'knight_military_capitao' }],
    scaling: 'str',
    pointType: 'ascension',
    ascensionId: 'knight_military_capitao',
  },
  {
    id: 'mil_cap_phalanx',
    scope: 'class',
    heroClass: 'knight',
    branch: 'defense',
    name: 'Falange',
    description: 'Escudo coletivo que absorve pressão inimiga.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'knight_military_capitao' }],
    scaling: 'str',
    pointType: 'ascension',
    ascensionId: 'knight_military_capitao',
  },
  {
    id: 'mil_cap_lance',
    scope: 'class',
    heroClass: 'knight',
    branch: 'offense',
    name: 'Investida do Capitão',
    description: 'Estocada pesada em alvo prioritário.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'knight_military_capitao' }],
    scaling: 'str',
    pointType: 'ascension',
    ascensionId: 'knight_military_capitao',
  },
  // Caminho Militar · General
  {
    id: 'mil_gen_decree',
    scope: 'class',
    heroClass: 'knight',
    branch: 'offense',
    name: 'Decreto de Guerra',
    description: 'Golpe devastador que marca o inimigo.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'knight_military_general' }],
    scaling: 'str',
    pointType: 'ascension',
    ascensionId: 'knight_military_general',
  },
  {
    id: 'mil_gen_banner',
    scope: 'class',
    heroClass: 'knight',
    branch: 'utility',
    name: 'Estandarte Imperial',
    description: 'Aura ofensiva para toda a party.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'knight_military_general' }],
    scaling: 'str',
    pointType: 'ascension',
    ascensionId: 'knight_military_general',
  },
  {
    id: 'mil_gen_siege',
    scope: 'class',
    heroClass: 'knight',
    branch: 'offense',
    name: 'Cerco Total',
    description: 'Explosão de dano físico em área.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'knight_military_general' }],
    scaling: 'str',
    pointType: 'ascension',
    ascensionId: 'knight_military_general',
  },
  // Caminho Marcial · Gladiador
  {
    id: 'mar_gla_slash',
    scope: 'class',
    heroClass: 'knight',
    branch: 'offense',
    name: 'Corte da Arena',
    description: 'Golpe rápido com alta prioridade.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'knight_martial_gladiador' }],
    scaling: 'dex',
    pointType: 'ascension',
    ascensionId: 'knight_martial_gladiador',
  },
  {
    id: 'mar_gla_feint',
    scope: 'class',
    heroClass: 'knight',
    branch: 'defense',
    name: 'Finta Mortal',
    description: 'Esquiva agressiva que prepara o próximo golpe.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'knight_martial_gladiador' }],
    scaling: 'dex',
    pointType: 'ascension',
    ascensionId: 'knight_martial_gladiador',
  },
  {
    id: 'mar_gla_bleed',
    scope: 'class',
    heroClass: 'knight',
    branch: 'offense',
    name: 'Sangrar',
    description: 'Ferimento profundo com dano contínuo.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'knight_martial_gladiador' }],
    scaling: 'dex',
    pointType: 'ascension',
    ascensionId: 'knight_martial_gladiador',
  },
  // Caminho Marcial · Mestre Marcial
  {
    id: 'mar_mes_flow',
    scope: 'class',
    heroClass: 'knight',
    branch: 'offense',
    name: 'Fluxo Marcial',
    description: 'Sequência fluida de ataques precisos.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'knight_martial_mestre' }],
    scaling: 'dex',
    pointType: 'ascension',
    ascensionId: 'knight_martial_mestre',
  },
  {
    id: 'mar_mes_zen',
    scope: 'class',
    heroClass: 'knight',
    branch: 'defense',
    name: 'Foco Zen',
    description: 'Concentração que reduz dano recebido.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'knight_martial_mestre' }],
    scaling: 'dex',
    pointType: 'ascension',
    ascensionId: 'knight_martial_mestre',
  },
  {
    id: 'mar_mes_rebuke',
    scope: 'class',
    heroClass: 'knight',
    branch: 'offense',
    name: 'Repreensão',
    description: 'Punição imediata ao alvo mais fraco.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'knight_martial_mestre' }],
    scaling: 'dex',
    pointType: 'ascension',
    ascensionId: 'knight_martial_mestre',
  },
  // Caminho Marcial · Campeão
  {
    id: 'mar_cam_crown',
    scope: 'class',
    heroClass: 'knight',
    branch: 'offense',
    name: 'Golpe da Coroa',
    description: 'Golpe supremo contra um único inimigo.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'knight_martial_campeao' }],
    scaling: 'dex',
    pointType: 'ascension',
    ascensionId: 'knight_martial_campeao',
  },
  {
    id: 'mar_cam_cyclone',
    scope: 'class',
    heroClass: 'knight',
    branch: 'offense',
    name: 'Ciclone da Arena',
    description: 'Rodopio ofensivo que atinge todos os inimigos.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'knight_martial_campeao' }],
    scaling: 'dex',
    pointType: 'ascension',
    ascensionId: 'knight_martial_campeao',
  },
  {
    id: 'mar_cam_glory',
    scope: 'class',
    heroClass: 'knight',
    branch: 'utility',
    name: 'Glória do Campeão',
    description: 'Surto de poder que cura o herói.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'knight_martial_campeao' }],
    scaling: 'dex',
    pointType: 'ascension',
    ascensionId: 'knight_martial_campeao',
  },
  // Evolução Nix — Caminho Arcano · Maga
  {
    id: 'arc_mag_bolt',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'offense',
    name: 'Rajada Arcana',
    description: 'Feixe de energia arcana concentrada.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'sorcerer_arcane_maga' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'sorcerer_arcane_maga',
  },
  {
    id: 'arc_mag_weave',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'defense',
    name: 'Trama Mística',
    description: 'Barreira arcana que reduz pressão inimiga.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'sorcerer_arcane_maga' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'sorcerer_arcane_maga',
  },
  {
    id: 'arc_mag_ward',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'utility',
    name: 'Selo Arcano',
    description: 'Fortalece aliados com proteção mágica.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'sorcerer_arcane_maga' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'sorcerer_arcane_maga',
  },
  // Caminho Arcano · Arquimaga
  {
    id: 'arc_arq_nova',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'offense',
    name: 'Nova Arcana',
    description: 'Explosão arcana em área.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'sorcerer_arcane_arquimaga' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'sorcerer_arcane_arquimaga',
  },
  {
    id: 'arc_arq_rift',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'offense',
    name: 'Fenda Arcana',
    description: 'Ruptura concentrada em alvo prioritário.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'sorcerer_arcane_arquimaga' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'sorcerer_arcane_arquimaga',
  },
  {
    id: 'arc_arq_bind',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'defense',
    name: 'Aprisionamento',
    description: 'Correntes arcanas que enfraquecem o inimigo.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'sorcerer_arcane_arquimaga' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'sorcerer_arcane_arquimaga',
  },
  // Caminho Arcano · Imperatriz Arcana
  {
    id: 'arc_imp_decree',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'offense',
    name: 'Decreto Arcano',
    description: 'Sentença mágica devastadora.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'sorcerer_arcane_imperatriz' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'sorcerer_arcane_imperatriz',
  },
  {
    id: 'arc_imp_crown',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'utility',
    name: 'Coroa Imperial',
    description: 'Aura ofensiva para toda a party.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'sorcerer_arcane_imperatriz' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'sorcerer_arcane_imperatriz',
  },
  {
    id: 'arc_imp_storm',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'offense',
    name: 'Tempestade Imperial',
    description: 'Tempestade arcana em campo aberto.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'sorcerer_arcane_imperatriz' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'sorcerer_arcane_imperatriz',
  },
  // Caminho Inato · Feiticeira
  {
    id: 'inn_fei_spark',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'offense',
    name: 'Faísca Inata',
    description: 'Descarga rápida de energia elemental.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'sorcerer_innate_feiticeira' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'sorcerer_innate_feiticeira',
  },
  {
    id: 'inn_fei_whisper',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'defense',
    name: 'Sussurro do Éter',
    description: 'Enfraquece a defesa inimiga com magia sutil.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'sorcerer_innate_feiticeira' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'sorcerer_innate_feiticeira',
  },
  {
    id: 'inn_fei_flame',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'offense',
    name: 'Chama Interior',
    description: 'Fogo inato que queima o alvo ao longo do tempo.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'sorcerer_innate_feiticeira' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'sorcerer_innate_feiticeira',
  },
  // Caminho Inato · Soberana Astral
  {
    id: 'inn_sob_comet',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'offense',
    name: 'Cometa Astral',
    description: 'Impacto estelar em área.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'sorcerer_innate_soberana' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'sorcerer_innate_soberana',
  },
  {
    id: 'inn_sob_veil',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'utility',
    name: 'Véu Astral',
    description: 'Cobertura estelar que fortalece aliados.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'sorcerer_innate_soberana' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'sorcerer_innate_soberana',
  },
  {
    id: 'inn_sob_lance',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'offense',
    name: 'Lança Estelar',
    description: 'Projétil preciso de energia astral.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'sorcerer_innate_soberana' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'sorcerer_innate_soberana',
  },
  // Caminho Inato · Filha do Éter
  {
    id: 'inn_fil_ether',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'offense',
    name: 'Toque do Éter',
    description: 'Golpe etéreo concentrado no alvo mais fraco.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'sorcerer_innate_filha_eter' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'sorcerer_innate_filha_eter',
  },
  {
    id: 'inn_fil_storm',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'offense',
    name: 'Tormenta Etérea',
    description: 'Vórtice de energia que atinge todos os inimigos.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'sorcerer_innate_filha_eter' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'sorcerer_innate_filha_eter',
  },
  {
    id: 'inn_fil_ascend',
    scope: 'class',
    heroClass: 'sorcerer',
    branch: 'utility',
    name: 'Ascensão Etérea',
    description: 'Canaliza o éter para restaurar a própria vida.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'sorcerer_innate_filha_eter' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'sorcerer_innate_filha_eter',
  },
  // Evolução Elara — Caminho Sagrado · Clériga Sagrada
  {
    id: 'sag_clr_light',
    scope: 'class',
    heroClass: 'priest',
    branch: 'offense',
    name: 'Luz Divina',
    description: 'Feixe sagrado contra o inimigo.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'priest_sacred_cleriga' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'priest_sacred_cleriga',
  },
  {
    id: 'sag_clr_smite',
    scope: 'class',
    heroClass: 'priest',
    branch: 'offense',
    name: 'Castigo Sagrado',
    description: 'Punição divina concentrada.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'priest_sacred_cleriga' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'priest_sacred_cleriga',
  },
  {
    id: 'sag_clr_ward',
    scope: 'class',
    heroClass: 'priest',
    branch: 'defense',
    name: 'Proteção Sagrada',
    description: 'Escudo divino para aliados.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'priest_sacred_cleriga' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'priest_sacred_cleriga',
  },
  // Caminho Sagrado · Alta Sacerdotisa
  {
    id: 'sag_alt_radiance',
    scope: 'class',
    heroClass: 'priest',
    branch: 'utility',
    name: 'Radiância Sagrada',
    description: 'Luz curativa que restaura aliados.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'priest_sacred_alta_sacerdotisa' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'priest_sacred_alta_sacerdotisa',
  },
  {
    id: 'sag_alt_chorus',
    scope: 'class',
    heroClass: 'priest',
    branch: 'utility',
    name: 'Coro Celestial',
    description: 'Cântico que fortalece toda a party.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'priest_sacred_alta_sacerdotisa' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'priest_sacred_alta_sacerdotisa',
  },
  {
    id: 'sag_alt_sanctuary',
    scope: 'class',
    heroClass: 'priest',
    branch: 'defense',
    name: 'Santuário',
    description: 'Zona sagrada de proteção intensa.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'priest_sacred_alta_sacerdotisa' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'priest_sacred_alta_sacerdotisa',
  },
  // Caminho Sagrado · Santa
  {
    id: 'sag_san_grace',
    scope: 'class',
    heroClass: 'priest',
    branch: 'utility',
    name: 'Graça Divina',
    description: 'Cura sagrada avançada.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'priest_sacred_santa' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'priest_sacred_santa',
  },
  {
    id: 'sag_san_judgment',
    scope: 'class',
    heroClass: 'priest',
    branch: 'offense',
    name: 'Julgamento Final',
    description: 'Sentença divina devastadora.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'priest_sacred_santa' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'priest_sacred_santa',
  },
  {
    id: 'sag_san_benediction',
    scope: 'class',
    heroClass: 'priest',
    branch: 'utility',
    name: 'Bênção Suprema',
    description: 'Bênção máxima para toda a equipe.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'priest_sacred_santa' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'priest_sacred_santa',
  },
  // Caminho da Vida · Clériga da Vida
  {
    id: 'vid_clr_renew',
    scope: 'class',
    heroClass: 'priest',
    branch: 'utility',
    name: 'Renovação',
    description: 'Cura vital sustentada.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'priest_life_cleriga' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'priest_life_cleriga',
  },
  {
    id: 'vid_clr_bloom',
    scope: 'class',
    heroClass: 'priest',
    branch: 'utility',
    name: 'Florescer',
    description: 'Regeneração suave para aliados.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'priest_life_cleriga' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'priest_life_cleriga',
  },
  {
    id: 'vid_clr_touch',
    scope: 'class',
    heroClass: 'priest',
    branch: 'utility',
    name: 'Toque Curativo',
    description: 'Toque preciso no aliado mais ferido.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'priest_life_cleriga' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'priest_life_cleriga',
  },
  // Caminho da Vida · Guardiã da Vida
  {
    id: 'vid_gua_aegis',
    scope: 'class',
    heroClass: 'priest',
    branch: 'defense',
    name: 'Égide Vital',
    description: 'Barreira de vida para proteger aliados.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'priest_life_guardia' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'priest_life_guardia',
  },
  {
    id: 'vid_gua_pulse',
    scope: 'class',
    heroClass: 'priest',
    branch: 'utility',
    name: 'Pulso de Vida',
    description: 'Onda curativa em toda a party.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'priest_life_guardia' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'priest_life_guardia',
  },
  {
    id: 'vid_gua_spring',
    scope: 'class',
    heroClass: 'priest',
    branch: 'utility',
    name: 'Fonte da Vida',
    description: 'Cura profunda no aliado prioritário.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'priest_life_guardia' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'priest_life_guardia',
  },
  // Caminho da Vida · Filha da Aurora
  {
    id: 'vid_fil_dawn',
    scope: 'class',
    heroClass: 'priest',
    branch: 'utility',
    name: 'Alvorada',
    description: 'Luz matinal que restaura vitalidade.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'priest_life_filha_aurora' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'priest_life_filha_aurora',
  },
  {
    id: 'vid_fil_aurora',
    scope: 'class',
    heroClass: 'priest',
    branch: 'utility',
    name: 'Aurora Restauradora',
    description: 'Cura transcendente em área.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'priest_life_filha_aurora' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'priest_life_filha_aurora',
  },
  {
    id: 'vid_fil_rebirth',
    scope: 'class',
    heroClass: 'priest',
    branch: 'utility',
    name: 'Renascimento',
    description: 'Renovação suprema para aliados em perigo.',
    maxRank: 3,
    requirements: [{ type: 'ascension', ascensionId: 'priest_life_filha_aurora' }],
    scaling: 'int',
    pointType: 'ascension',
    ascensionId: 'priest_life_filha_aurora',
  },
  // Monstros — acervo unificado (heróis podem desbloquear no futuro)
  { id: 'wild_bite', scope: 'monster', branch: 'offense', name: 'Mordida Selvagem', description: 'Mordida feroz do predador.', maxRank: 1, requirements: [], scaling: 'str', pointType: 'improvement' },
  {
    id: 'capelobo_brain_drink',
    scope: 'monster',
    branch: 'offense',
    name: 'Suga-Cérebro',
    description: 'Perfura o crânio com a tromba e drena a vitalidade do alvo.',
    maxRank: 1,
    requirements: [],
    scaling: 'str',
    pointType: 'improvement',
  },
  { id: 'goblin_stab', scope: 'monster', branch: 'offense', name: 'Facada', description: 'Golpe traiçoeiro com dano extra.', maxRank: 1, requirements: [], scaling: 'str', pointType: 'improvement' },
  { id: 'orc_smash', scope: 'monster', branch: 'offense', name: 'Pancada', description: 'Golpe pesado esmagador.', maxRank: 1, requirements: [], scaling: 'str', pointType: 'improvement' },
  { id: 'poison_spit', scope: 'monster', branch: 'offense', name: 'Cuspe Venenoso', description: 'Veneno corrosivo à distância.', maxRank: 1, requirements: [], scaling: 'int', pointType: 'improvement' },
  { id: 'ground_slam', scope: 'monster', branch: 'offense', name: 'Pancada Sísmica', description: 'Golpe de área que treme o chão.', maxRank: 1, requirements: [], scaling: 'str', pointType: 'improvement' },
  { id: 'regenerate', scope: 'monster', branch: 'utility', name: 'Regeneração', description: 'Recupera vida ao longo do combate.', maxRank: 1, requirements: [], scaling: 'str', pointType: 'improvement' },
  { id: 'slime_acid', scope: 'monster', branch: 'offense', name: 'Ácido', description: 'Corrói o alvo com dano mágico.', maxRank: 1, requirements: [], scaling: 'int', pointType: 'improvement' },
  { id: 'wraith_drain', scope: 'monster', branch: 'offense', name: 'Drenar Vida', description: 'Dreno mágico de vitalidade.', maxRank: 1, requirements: [], scaling: 'int', pointType: 'improvement' },
  { id: 'wraith_curse', scope: 'monster', branch: 'offense', name: 'Maldição', description: 'Reduz a defesa do alvo.', maxRank: 1, requirements: [], scaling: 'int', pointType: 'improvement' },
  { id: 'dragon_breath', scope: 'monster', branch: 'offense', name: 'Baforada', description: 'Fogo em área devastador.', maxRank: 1, requirements: [], scaling: 'int', pointType: 'improvement' },
  { id: 'dragon_bite', scope: 'monster', branch: 'offense', name: 'Mordida', description: 'Mordida devastadora.', maxRank: 1, requirements: [], scaling: 'str', pointType: 'improvement' },
  { id: 'saci_fire', scope: 'monster', branch: 'offense', name: 'Chama Elemental', description: 'Fogo concentrado no alvo.', maxRank: 1, requirements: [], scaling: 'int', pointType: 'improvement' },
  { id: 'saci_wind', scope: 'monster', branch: 'offense', name: 'Rajada de Vento', description: 'Vento cortante em área.', maxRank: 1, requirements: [], scaling: 'int', pointType: 'improvement' },
  {
    id: 'mapinguari_belly_roar',
    scope: 'monster',
    branch: 'offense',
    name: 'Rugido Torácico',
    description: 'Uivo grave da boca na barriga que fere e aterroriza a party.',
    maxRank: 1,
    requirements: [],
    scaling: 'str',
    pointType: 'improvement',
  },
];

export function getSkillById(skillId: string): SkillDefinition | undefined {
  return SKILL_CATALOG.find((skill) => skill.id === skillId);
}

export function getSkillsForHero(heroClass: string, ascensionId: string | null): SkillDefinition[] {
  return SKILL_CATALOG.filter((skill) => {
    if (skill.pointType === 'ascension') {
      if (ascensionId === null || !skill.ascensionId) return false;
      if (heroClass === 'knight' && isKnightEvolutionId(skill.ascensionId)) {
        return knightEvolutionUnlocksSkill(ascensionId, skill.ascensionId);
      }
      if (heroClass === 'sorcerer' && isSorcererEvolutionId(skill.ascensionId)) {
        return sorcererEvolutionUnlocksSkill(ascensionId, skill.ascensionId);
      }
      if (heroClass === 'priest' && isPriestEvolutionId(skill.ascensionId)) {
        return priestEvolutionUnlocksSkill(ascensionId, skill.ascensionId);
      }
      return skill.ascensionId === ascensionId;
    }
    if (skill.scope === 'universal') return true;
    if (skill.scope === 'class' && skill.heroClass === heroClass) return true;
    if (skill.scope === 'monster') return false;
    return false;
  });
}
