import { UpgradeDefinition } from './UpgradeDefinition';
import { applyUpgradeOverride } from './UpgradeOverrides';

export const UPGRADE_CATALOG: UpgradeDefinition[] = [
  {
    id: 'auto_battle_2',
    feature: 'auto_battle',
    level: 2,
    branch: 'combat',
    name: 'Auto-batalha II',
    description: 'Desbloqueia velocidade 2x na auto-batalha.',
    cost: 600,
    parents: ['battle_skill_slot_2'],
    requirements: [
      { type: 'min_stage', value: 2 },
      { type: 'min_battles_won', value: 10 },
    ],
  },
  {
    id: 'auto_battle_3',
    feature: 'auto_battle',
    level: 3,
    branch: 'combat',
    name: 'Auto-batalha III',
    description: 'Desbloqueia velocidade 3x na auto-batalha.',
    cost: 2500,
    parents: ['auto_battle_2'],
    requirements: [
      { type: 'upgrade_level', feature: 'auto_battle', minLevel: 2 },
      { type: 'min_stage', value: 6 },
    ],
  },
  // OFFLINE PROGRESS DESATIVADO (2026-07): upgrades removidos da árvore (código preservado).
  // {
  //   id: 'background_tick_1',
  //   feature: 'background_tick',
  //   level: 1,
  //   branch: 'combat',
  //   name: 'Tick idle I',
  //   description: 'O jogo avança em background mesmo com o painel fechado.',
  //   cost: 1000,
  //   parents: ['auto_battle_2'],
  //   requirements: [{ type: 'min_stage', value: 3 }],
  // },
  // {
  //   id: 'background_tick_2',
  //   feature: 'background_tick',
  //   level: 2,
  //   branch: 'combat',
  //   name: 'Tick idle II',
  //   description: 'Tick em background 2x mais frequente.',
  //   cost: 2500,
  //   parents: ['background_tick_1'],
  //   requirements: [
  //     { type: 'upgrade_level', feature: 'background_tick', minLevel: 1 },
  //     { type: 'min_stage', value: 5 },
  //   ],
  // },
  // AUTO-ABRIR BAÚS DESATIVADO (2026-08): quebra o jogo em alguns fluxos; código preservado.
  // {
  //   id: 'auto_open_chests_1',
  //   feature: 'auto_open_chests',
  //   level: 1,
  //   branch: 'chests',
  //   name: 'Auto-abrir baús I',
  //   description: 'Abre baús automaticamente quando disponíveis.',
  //   cost: 300,
  //   parents: ['battle_stats_1'],
  //   requirements: [{ type: 'min_stage', value: 3 }],
  // },
  {
    id: 'open_all_chests_1',
    feature: 'open_all_chests',
    level: 1,
    branch: 'chests',
    name: 'Abrir todos I',
    description: 'Desbloqueia o botão Abrir Todos no footer.',
    cost: 2500,
    parents: ['battle_skill_slot_2'],
    requirements: [{ type: 'min_stage', value: 3 }],
  },
  // AUTO-ABRIR BAÚS DESATIVADO (2026-08): nível II = autoOpenAllChests.
  // {
  //   id: 'open_all_chests_2',
  //   feature: 'open_all_chests',
  //   level: 2,
  //   branch: 'chests',
  //   name: 'Abrir todos II',
  //   description: 'Auto-abrir prioriza abrir todos quando há 2+ baús.',
  //   cost: 5000,
  //   parents: ['open_all_chests_1'],
  //   requirements: [
  //     { type: 'upgrade_level', feature: 'open_all_chests', minLevel: 1 },
  //     { type: 'min_chests_opened', value: 5 },
  //   ],
  // },
  // OTIMIZAR EQUIPE DESATIVADO (2026-08): remove auto-otimização que dispensa avaliar itens.
  // {
  //   id: 'optimize_loadout_1',
  //   feature: 'optimize_loadout',
  //   level: 1,
  //   branch: 'equipment',
  //   name: 'Otimizar equipe I',
  //   description: 'Desbloqueia o botão Otimizar equipe.',
  //   cost: 90,
  //   parents: [],
  //   requirements: [
  //     { type: 'min_stage', value: 3 },
  //     { type: 'min_battles_won', value: 8 },
  //   ],
  // },
  // {
  //   id: 'optimize_loadout_2',
  //   feature: 'optimize_loadout',
  //   level: 2,
  //   branch: 'equipment',
  //   name: 'Otimizar equipe II',
  //   description: 'Otimização disponível no loot em lote dos baús.',
  //   cost: 1000,
  //   parents: ['optimize_loadout_1'],
  //   requirements: [
  //     { type: 'upgrade_level', feature: 'optimize_loadout', minLevel: 1 },
  //     { type: 'min_stage', value: 5 },
  //   ],
  // },
  {
    id: 'auto_equip_loot_1',
    feature: 'auto_equip_loot',
    level: 1,
    branch: 'equipment',
    name: 'Auto-equipar I',
    description: 'Equipa loot recomendado sem abrir modal.',
    cost: 300,
    parents: ['battle_skill_slot_2'],
    requirements: [{ type: 'min_stage', value: 3 }],
  },
  {
    id: 'auto_equip_loot_2',
    feature: 'auto_equip_loot',
    level: 2,
    branch: 'equipment',
    name: 'Auto-equipar II',
    description: 'Auto-equipar sem notificações (silencioso).',
    cost: 1500,
    parents: ['auto_equip_loot_1'],
    requirements: [{ type: 'upgrade_level', feature: 'auto_equip_loot', minLevel: 1 }],
    // --- original (AUTO-ABRIR BAÚS DESATIVADO 2026-08) ---
    // parents: ['auto_equip_loot_1', 'open_all_chests_1'],
    // requirements: [
    //   { type: 'upgrade_level', feature: 'auto_equip_loot', minLevel: 1 },
    //   { type: 'upgrade_level', feature: 'auto_open_chests', minLevel: 1 },
    // ],
  },
  {
    id: 'item_stash_1',
    feature: 'item_stash',
    level: 1,
    branch: 'equipment',
    name: 'Baú de itens I',
    description: 'Desbloqueia o baú para guardar itens extras (24 slots).',
    cost: 600,
    parents: ['battle_skill_slot_2'],
    requirements: [
      { type: 'min_stage', value: 2 },
      { type: 'min_battles_won', value: 6 },
    ],
    // --- original (AUTO-ABRIR BAÚS DESATIVADO 2026-08) ---
    // parents: ['auto_open_chests_1'],
  },
  {
    id: 'item_stash_2',
    feature: 'item_stash',
    level: 2,
    branch: 'equipment',
    name: 'Baú de itens II',
    description: 'Aumenta a capacidade do baú para 36 slots.',
    cost: 2000,
    parents: ['item_stash_1'],
    requirements: [
      { type: 'upgrade_level', feature: 'item_stash', minLevel: 1 },
      { type: 'min_stage', value: 4 },
    ],
  },
  {
    id: 'item_stash_3',
    feature: 'item_stash',
    level: 3,
    branch: 'equipment',
    name: 'Baú de itens III',
    description: 'Aumenta a capacidade do baú para 48 slots.',
    cost: 5000,
    parents: ['item_stash_2'],
    requirements: [
      { type: 'upgrade_level', feature: 'item_stash', minLevel: 2 },
      { type: 'min_stage', value: 6 },
    ],
  },
  {
    id: 'divine_forge_1',
    feature: 'divine_forge',
    level: 1,
    branch: 'equipment',
    name: 'Forja Divina',
    description:
      'Desbloqueia a Forja Divina: fundir 9 itens da mesma raridade em um item superior, ou destruir itens por ouro.',
    cost: 600,
    parents: ['item_stash_1'],
    requirements: [{ type: 'min_stage', value: 4 }],
  },
  {
    id: 'improvement_reset_1',
    feature: 'improvement_reset',
    level: 1,
    branch: 'equipment',
    name: 'Reset de pontos',
    description:
      'Permite devolver pontos de aprimoramento de atributos e skills, um a um, para o saldo do herói.',
    cost: 5000,
    parents: ['divine_forge_1'],
    requirements: [
      { type: 'upgrade_level', feature: 'divine_forge', minLevel: 1 },
      { type: 'min_hero_level', value: 12 },
    ],
  },
  {
    id: 'improvement_reset_2',
    feature: 'improvement_reset',
    level: 2,
    branch: 'equipment',
    name: 'Reset de pontos em massa',
    description:
      'Permite zerar skills de aprimoramento e devolver o máximo possível de atributos do herói de uma vez.',
    cost: 10000,
    parents: ['improvement_reset_1'],
    requirements: [
      { type: 'upgrade_level', feature: 'improvement_reset', minLevel: 1 },
      { type: 'min_hero_level', value: 22 },
    ],
  },
  {
    id: 'log_filter_1',
    feature: 'log_filter',
    level: 1,
    branch: 'qol',
    name: 'Log resumido I',
    description: 'Filtra o log para eventos importantes.',
    cost: 1500,
    parents: ['auto_battle_3'],
    requirements: [{ type: 'min_stage', value: 2 }],
  },
  {
    id: 'battle_skill_slot_2',
    feature: 'battle_skill_slots',
    level: 1,
    branch: 'combat',
    name: 'Slot de skill II',
    description: 'Desbloqueia o 2º slot de skill ativa na batalha.',
    cost: 300,
    parents: [],
    requirements: [{ type: 'min_hero_level', value: 3 }],
  },
  {
    id: 'shop_refresh_1',
    feature: 'shop_refresh',
    level: 1,
    branch: 'economy',
    name: 'Renovar loja I',
    description: 'Desbloqueia renovar loja (2x por stage).',
    cost: 1000,
    parents: ['auto_battle_2'],
    requirements: [{ type: 'min_stage', value: 4 }],
  },
  {
    id: 'shop_refresh_2',
    feature: 'shop_refresh',
    level: 2,
    branch: 'economy',
    name: 'Renovar loja II',
    description: 'Até 5 renovações por stage.',
    cost: 2500,
    parents: ['shop_refresh_1'],
    requirements: [
      { type: 'upgrade_level', feature: 'shop_refresh', minLevel: 1 },
      { type: 'min_stage', value: 6 },
    ],
  },
  {
    id: 'shop_refresh_3',
    feature: 'shop_refresh',
    level: 3,
    branch: 'economy',
    name: 'Renovar loja III',
    description: 'Até 8 renovações por stage com 15% de desconto.',
    cost: 5000,
    parents: ['shop_refresh_2'],
    requirements: [
      { type: 'upgrade_level', feature: 'shop_refresh', minLevel: 2 },
      { type: 'min_battles_won', value: 20 },
    ],
  },
  {
    id: 'battle_skill_slot_3',
    feature: 'battle_skill_slots',
    level: 2,
    branch: 'combat',
    name: 'Slot de skill III',
    description: 'Desbloqueia o 3º slot de skill ativa na batalha.',
    cost: 2000,
    parents: ['battle_skill_slot_2'],
    requirements: [
      { type: 'upgrade_level', feature: 'battle_skill_slots', minLevel: 1 },
      { type: 'min_hero_level', value: 6 },
    ],
  },
  {
    id: 'hero_unlock_knight',
    feature: 'hero_unlock_knight',
    level: 1,
    branch: 'heroes',
    name: 'Desbloquear Galneon',
    description: 'Galneon entra na reserva — cavaleiro de linha de frente.',
    cost: 300,
    parents: ['battle_skill_slot_2'],
    requirements: [{ type: 'main_mission_completed', missionId: 'main:1-1' }],
    unlockHeroClass: 'knight',
  },
  {
    id: 'hero_unlock_priest',
    feature: 'hero_unlock_priest',
    level: 1,
    branch: 'heroes',
    name: 'Desbloquear Elara',
    description: 'Elara entra na reserva — suporte e cura.',
    cost: 600,
    parents: ['hero_unlock_knight'],
    requirements: [{ type: 'main_mission_completed', missionId: 'main:1-10' }],
    unlockHeroClass: 'priest',
  },
  {
    id: 'hero_unlock_berserker',
    feature: 'hero_unlock_berserker',
    level: 1,
    branch: 'heroes',
    name: 'Desbloquear Berserker',
    description: 'Torius entra na reserva — alto dano corpo a corpo.',
    cost: 1000,
    parents: ['hero_unlock_priest'],
    requirements: [{ type: 'main_mission_completed', missionId: 'main:1-20' }],
    unlockHeroClass: 'berserker',
  },
  {
    id: 'hero_unlock_archer',
    feature: 'hero_unlock_archer',
    level: 1,
    branch: 'heroes',
    name: 'Desbloquear Arqueira',
    description:
      'Rain entra na reserva — arqueira lendária de Kontempler, quase nunca avistada.',
    cost: 1800,
    parents: ['hero_unlock_berserker'],
    requirements: [{ type: 'main_mission_completed', missionId: 'main:1-30' }],
    unlockHeroClass: 'archer',
  },
  {
    id: 'hero_unlock_paladin',
    feature: 'hero_unlock_paladin',
    level: 1,
    branch: 'heroes',
    name: 'Desbloquear Paladino',
    description: 'Valerius entra na reserva — tanque equilibrado.',
    cost: 2500,
    parents: ['hero_unlock_archer'],
    requirements: [{ type: 'main_mission_completed', missionId: 'main:1-40' }],
    unlockHeroClass: 'paladin',
  },
];

export function getCatalogUpgradeById(id: string): UpgradeDefinition | undefined {
  return UPGRADE_CATALOG.find((entry) => entry.id === id);
}

export function getUpgradeById(id: string): UpgradeDefinition | undefined {
  const baseline = getCatalogUpgradeById(id);
  return baseline ? applyUpgradeOverride(baseline) : undefined;
}

export function listEffectiveUpgrades(): UpgradeDefinition[] {
  return UPGRADE_CATALOG.map((entry) => applyUpgradeOverride(entry));
}
