import { MapId } from './CampaignIds';

/**
 * Nomes temáticos por fase (1–50) em cada mapa.
 * Desafios/milestones podem sobrescrever via applyPhaseChallenge / blueprint.
 */
const STENDRA_PHASE_NAMES = [
  "Aventuras na Estrada",
  "Clareira dos Lobos",
  "Passagem dos Morcegos",
  "Trilha dos Ratos",
  "Alerta nas Fronteiras",
  "Posto de Madeira",
  "Vau do Riacho",
  "Bosque dos Goblins",
  "Colinas do Bandido",
  "Emboscada na Estrada",
  "Clareira Queimada",
  "Ninho na Copa",
  "Pedra do Caçador",
  "Vale das Teias",
  "Linha de Defesa",
  "Trilha do Musgo",
  "Caverna Úmida",
  "Ninho Venenoso",
  "Cruzeiro das Feras",
  "Marcha do Ato",
  "Clareira do Orvalho",
  "Senda dos Arqueiros",
  "Poço das Aranhas",
  "Campamento Saqueado",
  "Geada Fora de Época",
  "Meio do Caminho",
  "Bosque Silencioso",
  "Pedreira Abandonada",
  "Cânion Verde",
  "Pressão Crescente",
  "Fonte dos Espíritos",
  "Altar das Brasas",
  "Ponte de Cipós",
  "Mirante da Floresta",
  "Sombras Adiante",
  "Covil do Xamã",
  "Clareira das Brasas",
  "Trilha do Ogro",
  "Antro Rochoso",
  "Muralha de Ogro",
  "Antes do Assalto",
  "Guarnição da Fronteira",
  "Bosque Escarlate",
  "Passagem Estreita",
  "Último Fôlego",
  "Santuário Antigo",
  "Clareira do Julgamento",
  "Portal Elemental",
  "Despertar da Floresta",
  "Guardião Elemental"
] as const;

const GRUFTALL_PHASE_NAMES = [
  "Chegada Calorosa",
  "Ruínas Fumegantes",
  "Escória da Estrada",
  "Fornalha Fria",
  "Vigília das Chaminés",
  "Pátio de Cinzas",
  "Corredor de Brasa",
  "Fundição Quebrada",
  "Poço de Escória",
  "Chaminés Apressadas",
  "Galeria do Calor",
  "Bigorna Caída",
  "Tunel de Fuligem",
  "Casa do Ferreiro",
  "Linha de Defesa",
  "Ponte de Ferro",
  "Câmara das Brasas",
  "Forja Abandonada",
  "Duto Quente",
  "Marcha do Ato",
  "Pátio das Bigornas",
  "Rachadura de Magma",
  "Sopro de Cinzas",
  "Guarnição Ardente",
  "Prova do Segundo Ato",
  "Meio do Caminho",
  "Corrente de Fogo",
  "Cisterna Seca",
  "Torre de Fumaça",
  "Pressão Crescente",
  "Escória Endurecida",
  "Crisol Partido",
  "Minas de Brasa",
  "Salão Fundido",
  "Sombras Adiante",
  "Corredor Incandescente",
  "Guarda da Forja",
  "Pilar de Carvão",
  "Antro de Gonodor",
  "Antes do Assalto",
  "Último Fôlego",
  "Câmara do Caldeirão",
  "Fenda Flamejante",
  "Altar de Cinzas",
  "Vigília do Vulcão",
  "Portão de Escória",
  "Núcleo Ardente",
  "Respiradouro",
  "Chamado de Gonodor",
  "Centelha de Gonodor"
] as const;

const VALDRIS_PHASE_NAMES = [
  "Sombras na Entrada",
  "Ossário Menor",
  "Corredor Úmido",
  "Nicho das Aranhas",
  "Alerta nas Fronteiras",
  "Capela Deserta",
  "Procissão Rápida",
  "Cripta Rasa",
  "Salão dos Fêmures",
  "Linha de Defesa",
  "Galeria Putrefata",
  "Tumba Lacrada",
  "Cripta Putrefata",
  "Poço dos Vermes",
  "Marcha do Ato",
  "Nave Abandonada",
  "Sopro da Cripta",
  "Altar Quebrado",
  "Relicário Menor",
  "Prova do Segundo Ato",
  "Meio do Caminho",
  "Corredor das Almas",
  "Ossos Empilhados",
  "Câmara do Lamento",
  "Pressão Crescente",
  "Relíquia Infernal",
  "Nicho Maldito",
  "Passagem Sepulcral",
  "Trono de Osso",
  "Sombras Adiante",
  "Antes do Assalto",
  "Catacumba Profunda",
  "Véu da Morte",
  "Santuário Esquecido",
  "Último Fôlego",
  "Capela Negra",
  "Cripta Maior",
  "Corredor Espectral",
  "Poço Sem Fundo",
  "Guarda do Necromante",
  "Altar de Valdris",
  "Procissão Final",
  "Câmara do Véu",
  "Ossário Real",
  "Julgamento dos Mortos",
  "Portal Sepulcral",
  "Eco das Almas",
  "Trono Espectral",
  "Despertar de Valdris",
  "Espectro de Valdris"
] as const;

const MORTHAVEN_PHASE_NAMES = [
  "Portões do Ducado",
  "Pátio das Lanças",
  "Patrulha do Duque",
  "Muralha Exterior",
  "Alerta nas Fronteiras",
  "Guarnição Noturna",
  "Corredor das Tochas",
  "Muralha Sombria",
  "Torre de Vigia",
  "Linha de Defesa",
  "Salão dos Escudos",
  "Jardim Morto",
  "Salão Gelado",
  "Cripta do Castelo",
  "Marcha do Ato",
  "Ala dos Servos",
  "Ponte Levadiça",
  "Jardim de Almas",
  "Torre Norte",
  "Prova do Segundo Ato",
  "Meio do Caminho",
  "Salão do Trono Menor",
  "Guarda Negra",
  "Capela do Duque",
  "Pressão Crescente",
  "Corredor Gélido",
  "Torre das Corujas",
  "Arsenal Sombrio",
  "Pátio Interior",
  "Sombras Adiante",
  "Antes do Assalto",
  "Ala Nobre",
  "Salão das Tapeçarias",
  "Guarda Pessoal",
  "Último Fôlego",
  "Torre do Duque",
  "Câmara do Conselho",
  "Corredor Final",
  "Pátio da Execução",
  "Trono Antecipado",
  "Muralha Íntima",
  "Salão Escarlate",
  "Vigília do Castelo",
  "Portal do Senhor",
  "Julgamento Nobre",
  "Antessala",
  "Trono Negro",
  "Chamado do Duque",
  "Queda do Castelo",
  "Duque de Morthaven"
] as const;

const BROKEN_SKY_PHASE_NAMES = [
  "Primeiros Ventos",
  "Nuvem Baixa",
  "Ponte de Raios",
  "Penhasco Cortante",
  "Alerta nas Fronteiras",
  "Ninho de Grifos",
  "Corrente de Ar",
  "Torre dos Ventos",
  "Mirante Quebrado",
  "Linha de Defesa",
  "Tempestade Curta",
  "Plataforma Flutuante",
  "Garganta do Céu",
  "Ilha de Pedra",
  "Marcha do Ato",
  "Olho do Furacão",
  "Ponte Suspensa",
  "Ninho das Águias",
  "Rachadura Celeste",
  "Prova do Segundo Ato",
  "Meio do Caminho",
  "Altar dos Ventos",
  "Pico Relâmpago",
  "Caverna nas Nuvens",
  "Pressão Crescente",
  "Guarda Alada",
  "Tormenta Contida",
  "Arco Íris Partido",
  "Coluna de Ar",
  "Sombras Adiante",
  "Antes do Assalto",
  "Fortaleza Aérea",
  "Salão do Trovão",
  "Ninho do Colosso",
  "Último Fôlego",
  "Plataforma Final",
  "Véu de Nuvens",
  "Portal Tempestuoso",
  "Trono do Céu",
  "Julgamento Alado",
  "Corrente Quebrada",
  "Pico Sem Nome",
  "Altar do Raio",
  "Despertar da Hidra",
  "Céu Rachado",
  "Ninho Maior",
  "Olho Eterno",
  "Chamado do Colosso",
  "Queda do Firmamento",
  "Colosso do Céu Quebrado"
] as const;

const CRIMSON_ABYSS_PHASE_NAMES = [
  "Beira do Abismo",
  "Degrau Escarlate",
  "Fenda Infernal",
  "Eco do Vazio",
  "Alerta nas Fronteiras",
  "Patrulha Demoníaca",
  "Ponte de Ossos",
  "Poço Carmesim",
  "Altar Menor",
  "Linha de Defesa",
  "Corredor de Brasas",
  "Guarda do Fosso",
  "Sopro do Abismo",
  "Câmara Rubra",
  "Marcha do Ato",
  "Ninho de Demônios",
  "Relíquia Sangrenta",
  "Trono Rachado",
  "Véu Escarlate",
  "Prova do Segundo Ato",
  "Meio do Caminho",
  "Galeria das Garras",
  "Poço Sem Eco",
  "Altar do Príncipe",
  "Pressão Crescente",
  "Guarda Infernal",
  "Corredor Flamejante",
  "Câmara do Pacto",
  "Fenda Profunda",
  "Sombras Adiante",
  "Antes do Assalto",
  "Salão do Abismo",
  "Trono Menor",
  "Portal Carmesim",
  "Último Fôlego",
  "Antessala Rubra",
  "Guarda do Senhor",
  "Poço Final",
  "Altar do Vazio",
  "Julgamento Escarlate",
  "Corredor Último",
  "Câmara do Príncipe",
  "Véu Rasgado",
  "Chamado do Abismo",
  "Núcleo Carmesim",
  "Portal Infernal",
  "Trono Sangrento",
  "Despertar do Senhor",
  "Queda no Vazio",
  "Senhor do Abismo"
] as const;

const ETERNAL_FORGE_PHASE_NAMES = [
  "Portão da Forja",
  "Pátio das Bigornas",
  "Corrente Quente",
  "Fole Antigo",
  "Alerta nas Fronteiras",
  "Guarda do Metal",
  "Corredor de Aço",
  "Crisol Menor",
  "Torre de Carvão",
  "Linha de Defesa",
  "Salão das Moldes",
  "Ponte de Ferro",
  "Forja Contínua",
  "Câmara do Aço",
  "Marcha do Ato",
  "Ninho de Golems",
  "Bigorna Sagrada",
  "Duto Eterno",
  "Altar do Metal",
  "Prova do Segundo Ato",
  "Meio do Caminho",
  "Galeria Fundida",
  "Poço de Lava",
  "Guarda do Ferreiro",
  "Pressão Crescente",
  "Corredor Incandescente",
  "Torre da Bigorna",
  "Câmara Temperada",
  "Pilar de Aço",
  "Sombras Adiante",
  "Antes do Assalto",
  "Salão do Forjador",
  "Trono de Ferro",
  "Portal Temperado",
  "Último Fôlego",
  "Antessala Ígnea",
  "Guarda Eterna",
  "Crisol Maior",
  "Altar do Fogo",
  "Julgamento Metálico",
  "Corredor Final",
  "Câmara do Mestre",
  "Véu de Cinzas",
  "Chamado da Forja",
  "Núcleo Temperado",
  "Portal de Aço",
  "Trono Fundido",
  "Despertar do Forjador",
  "Martelo Eterno",
  "Forjador Eterno"
] as const;

const ANCIENT_GROVE_PHASE_NAMES = [
  "Clareira Antiga",
  "Raízes Profundas",
  "Trilha do Carvalho",
  "Fonte Sagrada",
  "Alerta nas Fronteiras",
  "Guarda do Bosque",
  "Cipó Espesso",
  "Altar de Musgo",
  "Ninho na Raiz",
  "Linha de Defesa",
  "Salão Verde",
  "Ponte de Troncos",
  "Bosque Eterno",
  "Câmara das Folhas",
  "Marcha do Ato",
  "Ninho dos Espíritos",
  "Pedra Ancestral",
  "Véu de Folhas",
  "Altar da Vida",
  "Prova do Segundo Ato",
  "Meio do Caminho",
  "Galeria Viva",
  "Poço de Seiva",
  "Guarda Arbórea",
  "Pressão Crescente",
  "Corredor de Cipós",
  "Torre de Carvalho",
  "Câmara do Guardião",
  "Pilar Verde",
  "Sombras Adiante",
  "Antes do Assalto",
  "Salão do Bosque",
  "Trono de Raízes",
  "Portal Natural",
  "Último Fôlego",
  "Antessala Viva",
  "Guarda Ancestral",
  "Clareira Final",
  "Altar do Guardião",
  "Julgamento Verde",
  "Corredor Último",
  "Câmara Sagrada",
  "Véu do Bosque",
  "Chamado Antigo",
  "Núcleo Vivo",
  "Portal de Folhas",
  "Trono Arbóreo",
  "Despertar do Guardião",
  "Coração do Bosque",
  "Guardião do Bosque"
] as const;

const TWILIGHT_TOWER_PHASE_NAMES = [
  "Degraus do Crepúsculo",
  "Pátio Crepuscular",
  "Torre Baixa",
  "Janela Âmbar",
  "Alerta nas Fronteiras",
  "Guarda da Torre",
  "Corredor Dourado",
  "Salão do Entardecer",
  "Mirante Roxo",
  "Linha de Defesa",
  "Ala das Sombras",
  "Ponte Interna",
  "Torre Média",
  "Câmara do Véu",
  "Marcha do Ato",
  "Ninho dos Corvos",
  "Relógio Parado",
  "Véu Crepuscular",
  "Altar do Crepúsculo",
  "Prova do Segundo Ato",
  "Meio do Caminho",
  "Galeria Âmbar",
  "Poço da Torre",
  "Guarda Noturna",
  "Pressão Crescente",
  "Corredor Violeta",
  "Torre Alta",
  "Câmara Estelar",
  "Pilar do Entardecer",
  "Sombras Adiante",
  "Antes do Assalto",
  "Salão da Sentinela",
  "Trono Crepuscular",
  "Portal Âmbar",
  "Último Fôlego",
  "Antessala Violeta",
  "Guarda Estelar",
  "Ápice da Torre",
  "Altar da Sentinela",
  "Julgamento Âmbar",
  "Corredor Final",
  "Câmara do Ápice",
  "Véu Noturno",
  "Chamado do Crepúsculo",
  "Núcleo Estelar",
  "Portal Violeta",
  "Trono do Entardecer",
  "Despertar da Sentinela",
  "Ápice Eterno",
  "Sentinela do Crepúsculo"
] as const;

const VOID_THRONE_PHASE_NAMES = [
  "Limiar do Vazio",
  "Pátio Sem Eco",
  "Degrau Negro",
  "Fenda Silente",
  "Alerta nas Fronteiras",
  "Guarda do Vazio",
  "Corredor Absoluto",
  "Salão Sem Nome",
  "Mirante Negro",
  "Linha de Defesa",
  "Ala do Nada",
  "Ponte Espectral",
  "Trono Antecipado",
  "Câmara Vazia",
  "Marcha do Ato",
  "Ninho do Vazio",
  "Relíquia Nula",
  "Véu Absoluto",
  "Altar do Silêncio",
  "Prova do Segundo Ato",
  "Meio do Caminho",
  "Galeria Negra",
  "Poço Sem Fundo",
  "Guarda Espectral",
  "Pressão Crescente",
  "Corredor Nulo",
  "Torre do Vazio",
  "Câmara Absoluta",
  "Pilar Negro",
  "Sombras Adiante",
  "Antes do Assalto",
  "Salão do Soberano",
  "Trono Menor",
  "Portal Nulo",
  "Último Fôlego",
  "Antessala Negra",
  "Guarda Absoluta",
  "Ápice do Vazio",
  "Altar do Soberano",
  "Julgamento Nulo",
  "Corredor Final",
  "Câmara do Trono",
  "Véu Rasgado",
  "Chamado do Vazio",
  "Núcleo Absoluto",
  "Portal Final",
  "Trono do Vazio",
  "Despertar do Soberano",
  "Coroa Nula",
  "Soberano do Vazio"
] as const;

const PHASE_NAMES_BY_MAP: Record<MapId, readonly string[]> = {
  stendra: STENDRA_PHASE_NAMES,
  gruftall: GRUFTALL_PHASE_NAMES,
  valdris: VALDRIS_PHASE_NAMES,
  morthaven: MORTHAVEN_PHASE_NAMES,
  broken_sky: BROKEN_SKY_PHASE_NAMES,
  crimson_abyss: CRIMSON_ABYSS_PHASE_NAMES,
  eternal_forge: ETERNAL_FORGE_PHASE_NAMES,
  ancient_grove: ANCIENT_GROVE_PHASE_NAMES,
  twilight_tower: TWILIGHT_TOWER_PHASE_NAMES,
  void_throne: VOID_THRONE_PHASE_NAMES,
};

/** Nome temático da fase; fallback só se o mapa/número for inválido. */
export function phaseDisplayName(mapId: MapId, phaseNumber: number): string {
  const names = PHASE_NAMES_BY_MAP[mapId];
  const index = Math.floor(phaseNumber) - 1;
  if (!names || index < 0 || index >= names.length) {
    return `Fase ${phaseNumber}`;
  }
  return names[index]!;
}
